// Generated by CoffeeScript 1.6.2
(function() {
  var Sequent, assert, vows;

  Sequent = require('../lib/sequent');

  vows = require('vows');

  assert = require('assert');

  vows.describe('Sequent').addBatch({
    'reset': {
      topic: new Sequent,
      'reset': {
        topic: function(seq) {
          var _this = this;

          seq.wait(1, function(num, name) {
            seq.reset();
            seq.wait(2, function(a, b) {
              return _this.callback(null, [a, b]);
            });
            seq.done(54321, 'Naomi Iizuka');
            return seq.done(4321, 'naomi iizuka');
          });
          seq.done();
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [4321, 'naomi iizuka']);
        }
      }
    },
    'wait - 1': {
      topic: new Sequent,
      'wait - done': {
        topic: function(seq) {
          var _this = this;

          seq.wait(1, function(num, name) {
            return _this.callback(null, [num, name]);
          });
          seq.done(4321, 'naomi iizuka');
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [4321, 'naomi iizuka']);
        }
      }
    },
    'wait - 2': {
      topic: new Sequent,
      'done - wait': {
        topic: function(seq) {
          var _this = this;

          seq.done(1234, 'nao iizuka');
          seq.wait(1, function(num, name) {
            return _this.callback(null, [num, name]);
          });
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [1234, 'nao iizuka']);
        }
      }
    },
    'wait - 3': {
      topic: new Sequent,
      'done - done - wait': {
        topic: function(seq) {
          var _this = this;

          seq.done(123, 'Lupin');
          seq.done(456, 'Lupin III');
          seq.wait(2, function(num, name) {
            return _this.callback(null, [num, name]);
          });
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [456, 'Lupin III']);
        }
      }
    },
    'wait - 4': {
      topic: new Sequent,
      'wait - done - done': {
        topic: function(seq) {
          var _this = this;

          seq.wait(2, function(num, name) {
            return _this.callback(null, [num, name]);
          });
          seq.done(123, 'Lupin');
          seq.done(456, 'Lupin III');
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [456, 'Lupin III']);
        }
      }
    },
    'wait - 5': {
      topic: new Sequent,
      'done - wait - done': {
        topic: function(seq) {
          var _this = this;

          seq.done(123, 'Lupin');
          seq.wait(2, function(num, name) {
            return _this.callback(null, [num, name]);
          });
          seq.done(789, 'Lupin IIII');
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [789, 'Lupin IIII']);
        }
      }
    },
    'wait - 6': {
      topic: new Sequent,
      'done - done - wait': {
        topic: function(seq) {
          var _this = this;

          seq.done(123, 'Lupin');
          seq.done(456, 'Lupin III');
          seq.wait(2, function(num, name) {
            return _this.callback(null, [num, name]);
          });
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [456, 'Lupin III']);
        }
      }
    },
    'wait - 7': {
      topic: new Sequent,
      'done - done - wait (with setTimeout)': {
        topic: function(seq) {
          var _this = this;

          setTimeout(function() {
            return seq.done(123, 'Lupin');
          }, 0);
          seq.done(456, 'Lupin III');
          seq.wait(2, function(num, name) {
            return _this.callback(null, [num, name]);
          });
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [123, 'Lupin']);
        }
      }
    },
    'wait - 8': {
      topic: new Sequent,
      'mature': {
        topic: function(seq) {
          var _this = this;

          setTimeout(function() {
            seq.done(123, 'Lupin');
            return seq.done(234, 'Lupin II');
          }, 100);
          seq.mature(456, 'Lupin III');
          seq.wait(2, function(num, name) {
            return _this.callback(null, [num, name]);
          });
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [456, 'Lupin III']);
        }
      }
    },
    'wait - 9': {
      topic: new Sequent,
      'mature': {
        topic: function(seq) {
          var _this = this;

          setTimeout(function() {
            seq.done(123, 'Lupin');
            return seq.done(234, 'Lupin II');
          }, 100);
          seq.wait(2, function(num, name) {
            return _this.callback(null, [num, name]);
          });
          seq.mature(456, 'Lupin III');
        },
        'we get num and name': function(err, result) {
          assert.isNull(err);
          return assert.deepEqual(result, [456, 'Lupin III']);
        }
      }
    },
    'wait - 10': {
      topic: new Sequent,
      'large sequent - wait - done': {
        topic: function(seq) {
          var i, num, results, _i,
            _this = this;

          results = [];
          seq.wait(100001, function() {
            return _this.callback(null, [results]);
          });
          i = 0;
          for (num = _i = 1000000; _i <= 1100000; num = ++_i) {
            results.push(i++);
            seq.done();
          }
        },
        'we get ordered array': function(err, result) {
          var _i, _results;

          assert.isNull(err);
          return assert.deepEqual(result, [
            (function() {
              _results = [];
              for (_i = 0; _i <= 100000; _i++){ _results.push(_i); }
              return _results;
            }).apply(this)
          ]);
        }
      }
    },
    'queue - 1': {
      topic: new Sequent,
      'queue (queue - flush)': {
        topic: function(seq) {
          var func, funcs, num, results, _i, _j, _len,
            _this = this;

          funcs = [];
          results = [];
          for (num = _i = 130; _i >= 100; num = --_i) {
            funcs.push(seq.queue((function(num) {
              return function() {
                return results.push(num);
              };
            })(num)));
          }
          for (_j = 0, _len = funcs.length; _j < _len; _j++) {
            func = funcs[_j];
            func();
          }
          seq.flush(function() {
            return _this.callback(null, [results]);
          });
        },
        'we get ordered array': function(err, result) {
          var _i, _results;

          assert.isNull(err);
          return assert.deepEqual(result, [
            (function() {
              _results = [];
              for (_i = 130; _i >= 100; _i--){ _results.push(_i); }
              return _results;
            }).apply(this)
          ]);
        }
      }
    },
    'queue - 2': {
      topic: new Sequent,
      'queue (flush - queue)': {
        topic: function(seq) {
          var func, funcs, num, results, _i, _j, _len,
            _this = this;

          funcs = [];
          results = [];
          seq.flush(function() {
            return _this.callback(null, [results]);
          });
          for (num = _i = 130; _i >= 100; num = --_i) {
            funcs.push(seq.queue((function(num) {
              return function() {
                return results.push(num);
              };
            })(num)));
          }
          for (_j = 0, _len = funcs.length; _j < _len; _j++) {
            func = funcs[_j];
            func();
          }
        },
        'we get ordered array': function(err, result) {
          var _i, _results;

          assert.isNull(err);
          return assert.deepEqual(result, [
            (function() {
              _results = [];
              for (_i = 130; _i >= 100; _i--){ _results.push(_i); }
              return _results;
            }).apply(this)
          ]);
        }
      }
    },
    'queue - 3': {
      topic: new Sequent,
      'large sequence - done - wait': {
        topic: function(seq) {
          var i, num, results, _i,
            _this = this;

          results = [];
          i = 0;
          for (num = _i = 1000000; _i <= 1100000; num = ++_i) {
            results.push(i++);
            seq.done();
          }
          seq.wait(100001, function() {
            return _this.callback(null, [results]);
          });
        },
        'we get ordered array': function(err, result) {
          var _i, _results;

          assert.isNull(err);
          return assert.deepEqual(result, [
            (function() {
              _results = [];
              for (_i = 0; _i <= 100000; _i++){ _results.push(_i); }
              return _results;
            }).apply(this)
          ]);
        }
      }
    },
    'queue - 4': {
      topic: new Sequent,
      'large queue': {
        topic: function(seq) {
          var func, funcs, i, results, _i, _j, _len, _ref,
            _this = this;

          funcs = [];
          results = [];
          for (i = _i = 1000000; _i <= 1100000; i = ++_i) {
            funcs.push(seq.queue(function() {
              return results.push(seq.i);
            }));
          }
          _ref = [funcs[3], funcs[0]], funcs[0] = _ref[0], funcs[3] = _ref[1];
          funcs.reverse();
          for (_j = 0, _len = funcs.length; _j < _len; _j++) {
            func = funcs[_j];
            func();
          }
          seq.flush(function() {
            return _this.callback(null, [results]);
          });
        },
        'we get ordered array': function(err, result) {
          var _i, _results;

          assert.isNull(err);
          return assert.deepEqual(result, [
            (function() {
              _results = [];
              for (_i = 0; _i <= 100000; _i++){ _results.push(_i); }
              return _results;
            }).apply(this)
          ]);
        }
      }
    }
  })["export"](module);

}).call(this);
